language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -q -r requirements.txt
before_script:
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Vw69Cewa0l/C2lDCBmEjbIbBDsbOAjROtmf4gZ5jG8FhDAltGtIBCDyJFy1Gl3skODvdpIdgZGCEduzQLegtiGz4gwM7oFCo22gdyAaZiasdCsTJx656ELqEp8IIglJGW5InEaO+I6gGFGgg4YwTynf9CPbyQlxHcLVn42TsJoQXeRenDYrPUmm5j1ADxiEnV8BdDDecAKYY1CzRoVR74seJ00ImaLOm2VmHLBsDozca12o+ZyxvkjLqU1188it0786M4Wy0SFT+nTcCP+bWmXHG539pH47ffnGAqAd7ZUwo7OvcpvA4WoE4kLnVfxR+r+L/XRjkxMG7nHqGg/zKXGAEOv74Qk8nUPq5MQXeefH7bLImhoY8g6a6td72h0FqVb5dKGfmZqW3KfRe/75KdXXCtiWEr/w7x6MpoO4ENe2REK7LTl46ORBx5TOVq5H9GTcgvE0GQI1rKDAXvgWU6oy1HsdyPD1yb1iUHHvDnpB81nFUmr/QfLH2Eq1EjRzu6ZBvTvxgZFMK3wJN9phih73uNMSSIIhPP6J1FRsB2TQTdHN2Fm6OwLgSMxwiqDnF4KxXuKKBijlBw7W6kuPYpWONWep/v/OiPkyJUsFWLr2pgdCyoFqted6GqUkHLbEiPLbrwHp+r91cX0m3hMv/2BM1fPXMPPjEdLF2zIeaDBE=
  app: download-series
  on:
    repo: rajeevrmenon97/series-downloader
